INSERT INTO MPA (MPA) VALUES ( 'G' );
INSERT INTO MPA (MPA) VALUES ( 'PG' );
INSERT INTO MPA (MPA) VALUES ( 'PG_13' );
INSERT INTO MPA (MPA) VALUES ( 'R' );
INSERT INTO MPA (MPA) VALUES ( 'NC_17' );

INSERT INTO GENRES (GENRE) VALUES ( 'COMEDY' );
INSERT INTO GENRES (GENRE) VALUES ( 'DRAMA' );
INSERT INTO GENRES (GENRE) VALUES ( 'CARTOON' );
INSERT INTO GENRES (GENRE) VALUES ( 'THRILLER' );
INSERT INTO GENRES (GENRE) VALUES ( 'DOCUMENTARY' );
INSERT INTO GENRES (GENRE) VALUES ( 'ACTION' );

INSERT INTO FRIENDSHIP_STATUS (STATUS) VALUES ( 'CONFIRMED' );
INSERT INTO FRIENDSHIP_STATUS (STATUS) VALUES ( 'NOT_CONFIRMED' );

INSERT INTO USERS (EMAIL, LOGIN, NAME, BIRTHDAY) VALUES ( 'TEST@MAIL.RU', 'LOGIN', 'NAME', '2025-01-01');
INSERT INTO USERS (EMAIL, LOGIN, NAME, BIRTHDAY) VALUES ( 'TEST2@MAIL.RU', 'LOGIN2', 'NAME2', '2025-01-02');
INSERT INTO USERS (EMAIL, LOGIN, NAME, BIRTHDAY) VALUES ( 'TEST3@MAIL.RU', 'LOGIN3', 'NAME3', '2025-01-03');
INSERT INTO USERS (EMAIL, LOGIN, NAME, BIRTHDAY) VALUES ( 'TEST4@MAIL.RU', 'LOGIN4', 'NAME4', '2025-01-04');

INSERT INTO FILMS (NAME, DESCRIPTION, RELEASE_DATE, DURATION, MPA_ID) VALUES ( 'NAME', 'DESCRIPTION', '2025-01-01', 60, (SELECT ID FROM MPA WHERE MPA = 'G'));
INSERT INTO FILMS (NAME, DESCRIPTION, RELEASE_DATE, DURATION, MPA_ID) VALUES ( 'NAME2', 'DESCRIPTION2', '2025-01-02', 60, (SELECT ID FROM MPA WHERE MPA = 'PG') );
INSERT INTO FILMS (NAME, DESCRIPTION, RELEASE_DATE, DURATION, MPA_ID) VALUES ( 'NAME3', 'DESCRIPTION3', '2025-01-03', 60, (SELECT ID FROM MPA WHERE MPA = 'PG_13') );
INSERT INTO FILMS (NAME, DESCRIPTION, RELEASE_DATE, DURATION, MPA_ID) VALUES ( 'NAME4', 'DESCRIPTION4', '2025-01-04', 60, (SELECT ID FROM MPA WHERE MPA = 'R') );

INSERT INTO FILMS_LIKES (FILM_ID, USER_ID) VALUES ( (SELECT ID FROM FILMS WHERE NAME ='NAME'), (SELECT ID FROM USERS WHERE NAME ='NAME'));
INSERT INTO FILMS_LIKES (FILM_ID, USER_ID) VALUES ( (SELECT ID FROM FILMS WHERE NAME ='NAME2'), (SELECT ID FROM USERS WHERE NAME ='NAME2'));
INSERT INTO FILMS_LIKES (FILM_ID, USER_ID) VALUES ( (SELECT ID FROM FILMS WHERE NAME ='NAME2'), (SELECT ID FROM USERS WHERE NAME ='NAME3'));
INSERT INTO FILMS_LIKES (FILM_ID, USER_ID) VALUES ( (SELECT ID FROM FILMS WHERE NAME ='NAME4'), (SELECT ID FROM USERS WHERE NAME ='NAME4'));


INSERT INTO USERS_FRIENDS (USER_ID, FRIEND_ID, FRIENDSHIP_STATUS_ID) VALUES ( (SELECT ID FROM USERS WHERE NAME ='NAME'),(SELECT ID FROM USERS WHERE NAME ='NAME2'), (SELECT ID FROM FRIENDSHIP_STATUS WHERE STATUS = 'CONFIRMED'));
INSERT INTO USERS_FRIENDS (USER_ID, FRIEND_ID, FRIENDSHIP_STATUS_ID) VALUES ( (SELECT ID FROM USERS WHERE NAME ='NAME2'),(SELECT ID FROM USERS WHERE NAME ='NAME'), (SELECT ID FROM FRIENDSHIP_STATUS WHERE STATUS = 'CONFIRMED'));
INSERT INTO USERS_FRIENDS (USER_ID, FRIEND_ID, FRIENDSHIP_STATUS_ID) VALUES ( (SELECT ID FROM USERS WHERE NAME ='NAME2'),(SELECT ID FROM USERS WHERE NAME ='NAME3'), (SELECT ID FROM FRIENDSHIP_STATUS WHERE STATUS = 'CONFIRMED'));
INSERT INTO USERS_FRIENDS (USER_ID, FRIEND_ID, FRIENDSHIP_STATUS_ID) VALUES ( (SELECT ID FROM USERS WHERE NAME ='NAME3'),(SELECT ID FROM USERS WHERE NAME ='NAME2'), (SELECT ID FROM FRIENDSHIP_STATUS WHERE STATUS = 'NOT_CONFIRMED'));
