CREATE TABLE IF NOT EXISTS mpa
(
    mpa_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mpa    VARCHAR(20) UNIQUE
)

CREATE TABLE IF NOT EXISTS genres
(
    genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre    VARCHAR(50) UNIQUE
)

CREATE TABLE IF NOT EXISTS films
(
    film_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(40)  NOT NULL,
    description VARCHAR(200) NOT NULL,
    releaseDate DATE         NOT NULL,
    duration    INTEGER      NOT NULL CHECK (duration > 0),
    mpa_id      INTEGER REFERENCES mpa (mpa_id)
)

CREATE TABLE IF NOT EXISTS users
(
    user_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(50) NOT NULL UNIQUE,
    login    VARCHAR(50) NOT NULL,
    name     VARCHAR(50),
    birthday DATE        NOT NULL CHECK (birthday <= CURRENT_DATE)
)

CREATE TABLE IF NOT EXISTS films_likes
(
    film_id INTEGER REFERENCES films (film_id),
    user_id INTEGER REFERENCES users (user_id),
    PRIMARY KEY (film_id, user_id)
)

CREATE TABLE IF NOT EXISTS films_genres
(
    film_id  INTEGER REFERENCES films (film_id),
    genre_id INTEGER REFERENCES genres (genre_id),
    PRIMARY KEY (film_id, genre_id)
)

CREATE TABLE IF NOT EXISTS friendship_status
(
    status_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status    VARCHAR(20) UNIQUE
)

CREATE TABLE IF NOT EXISTS users_friends
(
    user_id              INTEGER REFERENCES users (user_id),
    friend_id            INTEGER REFERENCES users (user_id),
    PRIMARY KEY (user_id, friend_id),
    friendship_status_id INTEGER REFERENCES friendship_status (status_id)
)

